version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    cooldown:
      default-days: 90
    groups:
      devcontainers-dependencies:
        patterns:
          - "*"
